Interactive Testing for 7-base_geometry.py
==========================================

7-base_geometry.py defines a Class `BaseGeometry` and methods `area` and `integer validator`.

def area(self): This method raises an Exception

	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
	>>> bg = BaseGeometry()
	>>> bg.area()
	Traceback (most recent call last):
	Exception: area() is not implemented

def integer_validator(self, name, value): This method validates the value passed to it.


Numbers
=======

	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
	>>> bg = BaseGeometry()

Integers
--------

	>>> bg.integer_validator("name", 2)
	>>> bg.integer_validator("age", 500)

Negative Integers
-----------------

	>>> bg.integer_validator("name", -3)
	Traceback (most recent call last):
	ValueError: name must be greater than 0

Zero
----

	>>> bg.integer_validator("age", 0)
	Traceback (most recent call last):
	ValueError: age must be greater than 0

===========
Non-Numbers
===========

Strings
-------

	>>> bg.integer_validator("name", "house")
	Traceback (most recent call last):
	TypeError: name must be an integer

Floats
------

	>>> bg.integer_validator("age", 7.3)
	Traceback (most recent call last):
	TypeError: age must be an integer

Tuple
-----

	>>> bg.integer_validator("age", (2,3))
	Traceback (most recent call last):
	TypeError: age must be an integer

Dictionary
----------

	>>> bg.integer_validator("age", {2,3})
	Traceback (most recent call last):
	TypeError: age must be an integer

List
----

	>>> bg.integer_validator("age", [3])
	Traceback (most recent call last):
	TypeError: age must be an integer

Bool
----

	>>> bg.integer_validation("age", True) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	AttributeError:
	
NaN
---
Type Nome;

	>>> bg.integer_validator("age", None)
	Traceback (most recent call last):
	TypeError: age must be an integer

  ::

Only one argument is passed:

	>>> bg.integer_validator("age") # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	TypeError: 

  ::

No argument is passed:

	>>> bg.integer_validator() # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	TypeError:

